### ISSUE TITLE
Trying to create a machine with a / crashes pcem

### ISSUE THREAD

**Issue by Derailedzack** [sarah-walker-pcem/pcem#77]
**Describe the bug**
pcem crashes when naming a machine with a slash after it
**To Reproduce**
1. Create a new machine and name it anything with a / after it
2. Click OK
3. Observe Segfault
**Expected behavior**
pcem shouldn't segfault
**Screenshots**
![image](https://user-images.githubusercontent.com/36719411/147857628-c1fe40e1-da09-4db3-be82-65c928126874.png)

**Emulator configuration**
 - N/A

**Host machine**
 - OS: Ubuntu 21.04
 - pcem vNext

**Additional context**
```
#0  __vfprintf_internal (s=0x0, format=0x555555ac08b5 "%s = %s\n", ap=ap@entry=0x7fffffffb180, mode_flags=mode_flags@entry=0) at vfprintf-internal.c:1359
#1  0x00007ffff6d6863a in __fprintf (stream=<optimized out>, format=<optimized out>) at fprintf.c:32
#2  0x0000555555846a34 in config_save ()
#3  0x000055555588b2b9 in saveconfig ()
#4  0x0000555555a10309 in config_selection_dlgproc ()
#5  0x0000555555a1109d in PCemDialogBox::processEvent(int, int, long) ()
#6  0x0000555555a11173 in PCemDialogBox::OnCommand(wxCommandEvent&) ()
#7  0x00007ffff7857661 in wxEvtHandler::ProcessEventIfMatchesId(wxEventTableEntryBase const&, wxEvtHandler*, wxEvent&) () at /lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
#8  0x00007ffff78579fa in wxEvtHandler::SearchDynamicEventTable(wxEvent&) () at /lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
#9  0x00007ffff7857a94 in wxEvtHandler::TryHereOnly(wxEvent&) () at /lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
#10 0x00007ffff7857b4b in wxEvtHandler::ProcessEventLocally(wxEvent&) () at /lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
#11 0x00007ffff7857bf1 in wxEvtHandler::ProcessEvent(wxEvent&) () at /lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
#12 0x00007ffff7d9057a in wxWindowBase::TryAfter(wxEvent&) () at /lib/x86_64-linux-gnu/libwx_gtk3u_core-3.0.so.0
#13 0x00007ffff785797b in wxEvtHandler::SafelyProcessEvent(wxEvent&) () at /lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
#14 0x00007ffff7c06317 in  () at /lib/x86_64-linux-gnu/libwx_gtk3u_core-3.0.so.0
#15 0x00007ffff6275724 in g_signal_emit_valist () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#16 0x00007ffff6275893 in g_signal_emit () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#17 0x00007ffff6697790 in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#18 0x00007ffff6275724 in g_signal_emit_valist () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#19 0x00007ffff6275893 in g_signal_emit () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#20 0x00007ffff6697314 in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#21 0x00007ffff694d25b in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#22 0x00007ffff6275724 in g_signal_emit_valist () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#23 0x00007ffff6275893 in g_signal_emit () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#24 0x00007ffff6761e6c in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#25 0x00007ffff625c2df in g_cclosure_marshal_VOID__BOXEDv () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#26 0x00007ffff6275724 in g_signal_emit_valist () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#27 0x00007ffff6275893 in g_signal_emit () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#28 0x00007ffff67597ab in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#29 0x00007ffff67616ab in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#30 0x00007ffff67622b3 in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#31 0x00007ffff6728ee0 in gtk_event_controller_handle_event () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#32 0x00007ffff68fc015 in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#33 0x00007ffff6942157 in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#34 0x00007ffff6257bcf in g_closure_invoke () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#35 0x00007ffff6281239 in  () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#36 0x00007ffff6275046 in g_signal_emit_valist () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#37 0x00007ffff6275893 in g_signal_emit () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#38 0x00007ffff690a754 in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#39 0x00007ffff67ac1f0 in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#40 0x00007ffff67ad4ab in gtk_main_do_event () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#41 0x00007ffff648c733 in  () at /lib/x86_64-linux-gnu/libgdk-3.so.0
#42 0x00007ffff64c3e36 in  () at /lib/x86_64-linux-gnu/libgdk-3.so.0
#43 0x00007ffff61618eb in g_main_context_dispatch () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#44 0x00007ffff61b4d28 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#45 0x00007ffff6160e53 in g_main_loop_run () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#46 0x00007ffff67a37fd in gtk_main () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#47 0x00007ffff7ba6bf5 in wxGUIEventLoop::DoRun() () at /lib/x86_64-linux-gnu/libwx_gtk3u_core-3.0.so.0
--Type <RET> for more, q to quit, c to continue without paging--
#48 0x00007ffff770bd41 in wxEventLoopBase::Run() () at /lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
#49 0x00007ffff7c11af2 in wxDialog::ShowModal() () at /lib/x86_64-linux-gnu/libwx_gtk3u_core-3.0.so.0
#50 0x0000555555a14979 in wx_dialogbox ()
#51 0x0000555555a10b81 in config_selection_open ()
#52 0x0000555555a200cc in wx_load_config ()
#53 0x0000555555a1a50c in Frame::ShowConfigSelection() ()
#54 0x0000555555a1a7ed in Frame::OnStopEmulationEvent(wxCommandEvent&) ()
#55 0x00007ffff7857661 in wxEvtHandler::ProcessEventIfMatchesId(wxEventTableEntryBase const&, wxEvtHandler*, wxEvent&) () at /lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
#56 0x00007ffff78579fa in wxEvtHandler::SearchDynamicEventTable(wxEvent&) () at /lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
#57 0x00007ffff7857a94 in wxEvtHandler::TryHereOnly(wxEvent&) () at /lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
#58 0x00007ffff7857b4b in wxEvtHandler::ProcessEventLocally(wxEvent&) () at /lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
#59 0x00007ffff7857bf1 in wxEvtHandler::ProcessEvent(wxEvent&) () at /lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
#60 0x00007ffff78585d2 in wxEvtHandler::ProcessPendingEvents() () at /lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
#61 0x00007ffff76d18ff in wxAppConsoleBase::ProcessPendingEvents() () at /lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
#62 0x00007ffff7b88c09 in wxApp::DoIdle() () at /lib/x86_64-linux-gnu/libwx_gtk3u_core-3.0.so.0
#63 0x00007ffff7b88d17 in  () at /lib/x86_64-linux-gnu/libwx_gtk3u_core-3.0.so.0
#64 0x00007ffff61617ef in g_main_context_dispatch () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#65 0x00007ffff61b4d28 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#66 0x00007ffff6160e53 in g_main_loop_run () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#67 0x00007ffff67a37fd in gtk_main () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#68 0x00007ffff7ba6bf5 in wxGUIEventLoop::DoRun() () at /lib/x86_64-linux-gnu/libwx_gtk3u_core-3.0.so.0
#69 0x00007ffff770bd41 in wxEventLoopBase::Run() () at /lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
#70 0x00007ffff76d33da in wxAppConsoleBase::MainLoop() () at /lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
#71 0x0000555555a1a040 in App::OnRun() ()
#72 0x00007ffff775f73d in wxEntry(int&, wchar_t**) () at /lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
#73 0x0000555555a0e3ce in main ()
```

**Comment by michael-manley** [comment]
This is because when you create the file it does /home/dir/.pcem/config//.cfg which is not valid. I added a function to not allow a filename with characters not allowed in the OS. Will make it more os dependent, but for now, just not allowing the windows charset of not allowed characters.
